spring:
  datasource:
    # URL ichidan neondb_owner:npg_... qismini butunlay olib tashladik
    url: jdbc:postgresql://ep-calm-bonus-an55v10d-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_8MXsbq1iYFha
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Thymeleaf
  thymeleaf:
    cache: false   # development da false, productionda true qiling
    prefix: classpath:/templates/
    suffix: .html

  # Spring Security session
  session:
    timeout: 24h

server:
  port: 8080

telegram:
  bot:
    token: ${TG_BOT_TOKEN:8481149034:AAEBaaP4Bbc-qM25Ftgn3HsOVTUOUEvKVoI}

tdlight:
  api-id: ${TD_LIGHT_API_ID:31578436}         # my.telegram.org dan olinadi
  api-hash: ${TD_LIGHT_API_HASH:0923d00b29c46473a406045c789c9f20}      # my.telegram.org dan olinadi
  sessions-dir: ${TD_SESSIONS_DIR:./sessions} # session fayllari

app:
  # Telegram Login Widget hash tekshirish uchun (token bilan bir xil)
  telegram-bot-token: ${TG_BOT_TOKEN:8481149034:AAEBaaP4Bbc-qM25Ftgn3HsOVTUOUEvKVoI}
  free-plan-max-configs: 10

scheduler:
  watcher:
    interval-ms: 30000
    max-messages-per-run: 10



#logging:
#  level:
#    uz.tgforward: INFO
#    org.telegram: WARN
#  file:
#    name: /var/log/tgforward/app.log
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 7
