spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/tgforward}
    username: ${DB_USERNAME:macbookpro}
    password: ${DB_PASSWORD:19801980}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Thymeleaf
  thymeleaf:
    cache: false   # development da false, productionda true qiling
    prefix: classpath:/templates/
    suffix: .html

  # Spring Security session
  session:
    timeout: 24h

server:
  port: 8080

telegram:
  bot:
    token: ${TG_BOT_TOKEN}

tdlight:
  api-id: ${TD_LIGHT_API_ID}         # my.telegram.org dan olinadi
  api-hash: ${TD_LIGHT_API_HASH}      # my.telegram.org dan olinadi
  sessions-dir: ${TD_SESSIONS_DIR:./sessions} # session fayllari

app:
  # Telegram Login Widget hash tekshirish uchun (token bilan bir xil)
  telegram-bot-token: ${TG_BOT_TOKEN}
  free-plan-max-configs: 10

scheduler:
  watcher:
    interval-ms: 30000
    max-messages-per-run: 10



#logging:
#  level:
#    uz.tgforward: INFO
#    org.telegram: WARN
#  file:
#    name: /var/log/tgforward/app.log
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 7
